# Generated by Django 5.0.14 on 2025-09-21 19:34

import core.models
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_datafile_file_size_datafile_original_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='file',
            field=models.FileField(storage=core.storage.get_media_storage, upload_to=core.models.dataset_upload_path),
        ),
    ]
