name: Deploy to Cloud Run Dev

on:
  push:
    branches: [ "dev" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_DEV }}
  REGION: us-central1
  REPO: axi-dev-repo
  SERVICE_NAME: axi-dev-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_DEV }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Set gcloud project
        run: gcloud config set project "$PROJECT_ID"

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker "$REGION-docker.pkg.dev"

      - name: Build and Push
        run: |
          IMAGE="$REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$SERVICE_NAME:${GITHUB_SHA::7}"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Get Cloud SQL connection name
        id: sql
        run: |
          CONN_NAME=$(gcloud sql instances describe "${{ secrets.CLOUD_SQL_INSTANCE_DEV }}" \
            --project "$PROJECT_ID" --format='value(connectionName)')
          echo "CONN_NAME=$CONN_NAME" >> $GITHUB_ENV

      - name: Deploy to Cloud Run Dev
        run: |
          gcloud run deploy "$SERVICE_NAME" \
            --image "$IMAGE" \
            --region "$REGION" \
            --platform managed \
            --allow-unauthenticated \
            --set-cloudsql-instances "$CONN_NAME" \
            --set-env-vars "ENVIRONMENT=dev" \
            --set-env-vars "DEBUG=true,SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY_DEV }}" \
            --set-env-vars "DB_ENGINE=postgres,DB_NAME=axi_dev,DB_USER=axi_dev,DB_PASSWORD=${{ secrets.DB_PASSWORD_DEV }},DB_HOST=/cloudsql/$CONN_NAME" \
            --set-env-vars "USE_GCS=true,GS_BUCKET_NAME=${{ secrets.GS_BUCKET_NAME_DEV }}" \
            --set-env-vars "LOG_LEVEL=INFO,WEB_CONCURRENCY=2" \
            --cpu=1 --memory=512Mi --timeout=300

      - name: Bootstrap Users Dev
        run: |
          echo "Creating bootstrap users for dev..."
          gcloud run jobs create bootstrap-users-dev-${{ github.run_number }} \
            --image "$IMAGE" \
            --region "$REGION" \
            --set-cloudsql-instances "$CONN_NAME" \
            --set-env-vars "SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY_DEV }},DB_ENGINE=postgres,DB_NAME=axi_dev,DB_USER=axi_dev,DB_PASSWORD=${{ secrets.DB_PASSWORD_DEV }},DB_HOST=/cloudsql/$CONN_NAME" \
            --command python \
            --args "manage.py,bootstrap" \
            --execute-now \
            --wait
          echo "Bootstrap dev completed!"

